# Default build settings
[build]
  command = "./scripts/netlify-build.sh"
  functions = "dist/netlify"
  publish = ""
  environment = { CI = "true" }


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirects for all images to CDN
[[redirects]]
  from = "/images/*"
  to = "https://dt7zex2d2lk4u.cloudfront.net/images/:splat"
  status = 200

# Support CORS on JSON files
[[headers]]
  for = "/*.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
